### PR TITLE
Fixed : Add Server Name Indication (SNI)

### LINKED ISSUE #59: Unable to add Server Name Indication
Hi, 
I'm trying to set **Server Name Indication (SNI)** using SSLParameters, but in `"org/wildfly/openssl/wildfly-openssl/1.0.4.Final/wildfly-openssl-1.0.4.Final.jar!/org/wildfly/openssl/OpenSSLEngine.class`", "`OpenSSLEngine.setSSLParameters(SSLParameters sslParameters)`" doesn't apply "SNIServerName", it looks like a bug to me, can anyone confirm or suggest an alternative way to set SNI?  Thanks.

### PR DESCRIPTION
**Pull request by vishwajeetdusane**
This pull request fixed #59. Server name indication (SNI) is set during SSL handshake. OpenSSL API `SSL_ctrl` can be used to set SNI. Added a feature to set SNI from `OpenSSLEngine`.

Test executed.
1. SNI is not set before this change.
2. Verified SNI is set for HTTPS requests after this change.
3. Verified when multiple SSL handshake initiated from same SocketFactory instance. Each SSL handshake has its own host name set as SNI.

### CODE REVIEW

File: java/src/main/java/org/wildfly/openssl/OpenSSLEngine.java [hunk 1]
```diff
@@ -28,11 +32,8 @@
 import java.util.concurrent.atomic.AtomicIntegerFieldUpdater;
 import java.util.logging.Level;
 import java.util.logging.Logger;
-import javax.net.ssl.SSLEngine;
-import javax.net.ssl.SSLEngineResult;
-import javax.net.ssl.SSLException;
-import javax.net.ssl.SSLParameters;
-import javax.net.ssl.SSLSession;
+
+import static org.wildfly.openssl.Messages.MESSAGES;
```
Comment (ThomasMarquardt) [inline java/src/main/java/org/wildfly/openssl/OpenSSLEngine.java]: Reordering imports, although seemingly harmless, can lead to merge conflicts.

File: java/src/main/java/org/wildfly/openssl/OpenSSLEngine.java [hunk 2]
```diff
@@ -1282,6 +1302,16 @@ public void setSSLParameters(SSLParameters sslParameters) {
                 }
                 SSL.getInstance().setSSLVerify(ssl, value, DEFAULT_CERTIFICATE_VALIDATION_DEPTH);
             }
+
+            if(clientMode) {
+                List<SNIServerName> sniHostNames = sslParameters.getServerNames();
+                if(sniHostNames != null && !sniHostNames.isEmpty()) {
+                    for(SNIServerName serverName : sniHostNames) {
+                        SSL.getInstance().setServerNameIndication(ssl,
+                            serverName.toString());
```
Comment (ThomasMarquardt) [inline java/src/main/java/org/wildfly/openssl/OpenSSLEngine.java]: I am not sure why SSLParameters.getServerNames returns a list of SNIServerName instead of a list of SNIHostName.  It would be safer to call SNIHostName.getAsciiName() than to rely on the implementation of toString().  For example:  

if (serverName.getType() == StandardConstants.SNI_HOST_NAME) {
  SSL.getInstance().setServerNameIndication(ssl, ((SNIHostName) serverName).getAsciName());
}

File: libwfssl/include/wfssl.h [hunk 3]
```diff
@@ -550,6 +551,7 @@ typedef struct {
     void (*SSL_set_accept_state)(SSL *s);
     void (*SSL_set_bio)(SSL *s, BIO *rbio, BIO *wbio);
     int (*SSL_set_cipher_list)(SSL *s, const char *str);
+    int (*SSL_set_tlsext_host_name)(SSL *s, const char *hostName);
```
Comment (ThomasMarquardt) [inline libwfssl/include/wfssl.h]: I believe this should be removed since you are not using it and it is a macro not a method that needs to be late bound.

File: libwfssl/src/ssl.c [hunk 4]
```diff
@@ -844,6 +845,34 @@ WF_OPENSSL(jboolean, setCipherSuite)(JNIEnv *e, jobject o, jlong ctx, jstring ci
     return rv;
 }
 
+WF_OPENSSL(jboolean, setServerNameIndication)(JNIEnv *e, jobject o, jlong ssl,
+jstring hostName)
+{
+#pragma comment(linker, "/EXPORT:"__FUNCTION__"="__FUNCDNAME__)
+    jboolean rv = JNI_TRUE;
+    SSL *ssl_ = J2P(ssl, SSL *);
+    TCN_ALLOC_CSTRING(hostName);
```
Comment (ThomasMarquardt) [inline libwfssl/src/ssl.c]: It appears that this allocation is leaked if we return on lines 858 or 863.

File: java/src/main/java/org/wildfly/openssl/OpenSSLEngine.java (hunk 1 above)
Comment (vishwajeetdusane) [reply java/src/main/java/org/wildfly/openssl/OpenSSLEngine.java]: Most of the java classes are already organized imports alphabetically. Retaining this standard for this file as well.

**Comment by ThomasMarquardt** [comment]
+1 looks good to me

**Comment by vishwajeetdusane** [comment]
Thank you @ThomasMarquardt  and @stuartwdouglas.
